### ISSUE TITLE
Packaging for nix

### ISSUE THREAD

**Issue by youhaveme9** [THEGOLDENPRO/devgoldyutils#5]
Hey !
I was trying to update the mov-cli in nixpkgs from version 1.5.4 -> 4.3.14 and found out that `devgoldyutils` is one of the dependencies, but its not present in nixpkgs.

Will it be a good idea to add it in nixpkgs?

If it is then I would like to package and maintain it in nixpkgs.

PR for updating mov-cli: https://github.com/NixOS/nixpkgs/pull/311026

**Comment by THEGOLDENPRO** [comment]
Yeah it would great if you could add `devgoldyutils` as a package on nixpkgs. 👍 Thanks, in advance.

**Comment by youhaveme9** [comment]
I have raised a pr for adding this in nixpkgs
https://github.com/NixOS/nixpkgs/pull/312461 
I request you to review it.

**Comment by THEGOLDENPRO** [comment]
I don't know much about NixOS as I haven't used it so I asked my friend who does and he said it's all good but a "version check" was missing.

I never touched Nix so this is all new to me, sorry.

**Comment by youhaveme9** [comment]
> I don't know much about NixOS as I haven't used it so I asked my friend who does and he said it's all good but a "version check" was missing.
> 
> I never touched Nix so this is all new to me, sorry.

No problem
It got merged 🎉

**Comment by THEGOLDENPRO** [comment]
Thank you very much. 👍
